### ISSUE TITLE
Change the file name for COPYING to CONTRIBUTING

### ISSUE THREAD

**Issue by jskortel** [VTT-ProperTune/OpenPFC#39]
The file for copyright transfer notification is named as COPYING. GitHub interprets the file to contain a license and lists it in the About sections as: "AGPL-3.0, Unknown licenses found". The AGPL license in interpreted based on the LICENSE file. The file name for the COPYING should be changed to e.g. CONTRIBUTING.

**Comment by ahojukka5** [comment]
I agree that we should either change the file name or configure repository so that it doesn't interpret the file like it is doing now.

Usually, the contributing file is having instructions how to contribute to the project (see e.g. https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md), so I don't know is it a good idea to use CONTRIBUTING as a new file name if we decide to change it to something else than COPYING. COPYING itself sounds quite relevant file name for me.

**Comment by ahojukka5** [comment]
Actually, I'm quite sure that if we rename it to CONTRIBUTING, then it will be shown when someone is trying to do pull request, so that might not be the best option. The best would be if we can explicitly define somewhere that what is the name of the license file. I don't know is this possible.

**Comment by jskortel** [comment]
So, is it that GitHub interprets the license file based on the original interpretation (i.e. it will be a license file even if the file name has been changed), or does GitHub interpret the license just based on the file name? At least the LICENSE file is now recognised. Renaming the COPYING file to CONTRIBUTING would make sense as it gives important information about copyright transfer when contributing to OpenPFC. Another proposal for the file name could be COPYRIGHT, as the file explains how the copyright is treated when contributing to OpenPFC.

If GitHub interprets the license based on the original interpretation (i.e. the file is defined as a license file independent how the file name may have been changed), it can be overcome with deleting and creating new file(s). Might be best to first define what is to be communicated with these files and then just test how GitHub works.

**Comment by ahojukka5** [comment]
> Might be best to first define what is to be communicated with these files and then just test how GitHub works.

I agree. What about, if we have `CONTRIBUTING.md` where we also describe some general guidelines how to contribute to project, and embed contents of COPYING to that file? For now, it would be enough to just change the file name and we can add some other content later on.

**Comment by jskortel** [comment]
Sorry for a quite a long delay in replying. Yes that might work. At least in a cloned repo this seems to work logically. The repo shows just one license (AGPL) and the CONTRIBUTING.md contains instructions how to contribute and the copyright transfer notice.

**Comment by ahojukka5** [comment]
The file renaming worked. Now it only shows one license: AGPL-3.
